ERPProject/Controllers/ArticleController.cs
using ERPProject.Entity;
using ERPProject.Models.Article;
using ERPProject.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ERPProject.Controllers
{
    [Authorize(Roles = "warehouser, admin")]
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;
        public ArticleController(IArticleService service)
        {
            _articleService = service;
        }
        // GET: Article
        public ActionResult Index()
        {
            var articles = _articleService.GetAll().Select(x => new ArticleIndexModelView
            {
                Id = x.Id,
                Name = x.Name,
                Code = x.Code,
                Amount = x.Amount,
                ArticleGroup = x.ArticleGroup.Name,
                Price = x.Price,
                Unit = x.Unit,
                WarehouseName = x.Warehouse.Name
            });
            return View(articles);
        }

        public ActionResult Create()
        {
            ViewBag.ArticleGroups = new SelectList(_articleService.GetArticleGroups(), "Id", "Name");
            ViewBag.Warehouses = new SelectList(_articleService.GetWarehouses(), "Id", "Name");
            return View(new ArticleCreateModelView());
        }
        [HttpPost]
        public ActionResult Create(ArticleCreateModelView model)
        {
            ViewBag.ArticleGroups = new SelectList(_articleService.GetArticleGroups(), "Id", "Name");
            ViewBag.Warehouses = new SelectList(_articleService.GetWarehouses(), "Id", "Name");
            if (ModelState.IsValid)
            {
                Article article = new Article
                {
                    Name = model.Name,
                    Code = model.Code,
                    Amount = model.Amount,
                    ArticleGroupId = model.ArticleGroupId,
                    Price = model.Price,
                    Unit = model.Unit,
                    WarehouseId = model.WarehouseId
                };
                _articleService.AddArticle(article);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            _articleService.DeleteArticle(id);
            return RedirectToAction("Index");
        }
    }
}

ERPProject/Controllers/ContractorController.cs
using ERPProject.Entity;
using ERPProject.Models.Contractor;
using ERPProject.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ERPProject.Controllers
{
    [Authorize(Roles = "warehouser, admin")]
    public class ContractorController : Controller
    {
        private readonly IContractorService cService;
        public ContractorController(IContractorService contractorService)
        {
            cService = contractorService;
        }
        // GET: Contractor
        public ActionResult Index()
        {
            var list = cService.GetAll().Select(contractor => new ContractorIndexViewModel()
            {
                Name = contractor.Name,
                Id = contractor.Id,
                Code = contractor.Code,
                PostCode = contractor.PostCode,
                Address = contractor.Address,
                Country = contractor.Country,
                City = contractor.City,
                CountrySign = contractor.CountrySign,
                TIN = contractor.TIN
            });
            return View(list.ToList());
        }

        public ActionResult Create()
        {
            return View(new ContractorCreateViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ContractorCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                Contractor contractor = new Contractor
                {
                    Name = model.Name,
                    Code = model.Code,
                    CountrySign = model.CountrySign,
                    Country = model.Country,
                    City = model.City,
                    TIN = model.TIN,
                    PostCode = model.PostCode,
                    Address = model.Address

                };
                cService.Create(contractor);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Details(int id)
        {


            var model = cService.GetById(id);
            var cDetails = new ContractorDetailsViewModel
            {
                Name = model.Name,
                Code = model.Code,
                CountrySign = model.CountrySign,
                Country = model.Country,
                City = model.City,
                TIN = model.TIN,
                PostCode = model.PostCode,
                Address = model.Address
            };
            return View(cDetails);
        }

        public ActionResult Delete(int id)
        {
            cService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

ERPProject/Controllers/InventoryController.cs
using ERPProject.Entity;
using ERPProject.Models.Inventory;
using ERPProject.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ERPProject.Controllers
{
    [Authorize(Roles = "admin")]
    public class InventoryController : Controller
    {
        // GET: Inventory

        private readonly IInventoryService _inventoryService;
        private readonly IEmployeeService _employeeService;

        public InventoryController(IInventoryService inventoryService, IEmployeeService employeeService)
        {

            _inventoryService = inventoryService;
            _employeeService = employeeService;
        }

        // GET: Inventory
        public ActionResult Index()
        {
            Uri MyUrl = Request.UrlReferrer;
            var inventories = _inventoryService.GetAll().Select(x => new InventoryIndexModelView
            {
                Id = x.Id,
                Code = x.Code,
                EmployeeId = x.EmployeeId,
                EmployeeFullName = x.Employee.FullName,
                InventoryGroup = x.InventoryGroup,
                InventoryNumber = x.InventoryNumber,
                Name = x.Name
            }).ToList();

            return View(inventories);
        }

        // GET: Inventory/Details/5
        public ActionResult Details(int id)
        {
            var inventory = _inventoryService.GetById(id);
            InventoryDetailsModelView model = new InventoryDetailsModelView
            {
                Name = inventory.Name,
                Code = inventory.Code,
                EmployeeFullName = inventory.Employee.FullName,
                InventoryGroup = inventory.InventoryGroup,
                InventoryNumber = inventory.InventoryNumber
            };
            return View(model);
        }

        // GET: Inventory/Create
        public ActionResult Create()
        {
            var model = new InventoryCreateModelView();
            @ViewBag.Employees = new SelectList(_employeeService.GetAll(), "Id", "FullName");
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(InventoryCreateModelView model)
        {
            if (ModelState.IsValid)
            {
                var inventory = new Inventory
                {
                    EmployeeId = model.EmployeeId,
                    Name = model.Name,
                    Code = model.Code,
                    InventoryNumber = model.InventoryNumber,
                    InventoryGroup = model.InventoryGroup
                };
                _inventoryService.Create(inventory);

                return RedirectToAction("Index");
            }
            return View();
        }


        // GET: Inventory/Edit/5
        public ActionResult Edit(int id)
        {
            @ViewBag.Employees = new SelectList(_employeeService.GetAll(), "Id", "FullName");
            var inventory = _inventoryService.GetById(id);
            InventoryEditModelView model = new InventoryEditModelView
            {
                Name = inventory.Name,
                Code = inventory.Code,
                EmployeeId = inventory.Employee.Id,
                InventoryGroup = inventory.InventoryGroup,
                InventoryNumber = inventory.InventoryNumber
            };
            return View(model);
        }

        // POST: Inventory/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(InventoryEditModelView inventory)
        {

            if (ModelState.IsValid)
            {
                Inventory model = new Inventory
                {
                    Name = inventory.Name,
                    Code = inventory.Code,
                    EmployeeId = inventory.EmployeeId,
                    InventoryGroup = inventory.InventoryGroup,
                    InventoryNumber = inventory.InventoryNumber,
                    Id = inventory.Id
                };
                _inventoryService.Update(model);
                return RedirectToAction("Index");
            }

            return View();


        }

        public ActionResult Delete(int id)
        {
            _inventoryService.Delete(id);
            return RedirectToAction("Index");
        }
        public JsonResult IsCodeExist(string code)
        {
            return Json(!_inventoryService.IsCodeExist(code), JsonRequestBehavior.AllowGet);
        }
        public JsonResult IsInventoryNumberExist(string inventoryNumber)
        {
            return Json(!_inventoryService.IsInventoryNumberExist(inventoryNumber), JsonRequestBehavior.AllowGet);
        }

    }
}

ERPProject/Controllers/OrderController.cs
using ERPProject.Entity;
using ERPProject.Models.Order;
using ERPProject.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace ERPProject.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderService _oService;
        private readonly IContractorService _cService;
        private readonly IArticleService _aService;
        private readonly ILoginService _lService;
        public OrderController(IOrderService orderService, IContractorService contractorService, IArticleService articleService, ILoginService loginService)
        {
            _oService = orderService;
            _cService = contractorService;
            _aService = articleService;
            _lService = loginService;
        }
        // GET: Order
        public ActionResult Index()
        {

            var orders = _oService.GetOrders().Select(x => new OrderIndexModelView
            {
                Id = x.Id,
                Code = x.Code,
                ContractorName = x.Contractor.Name,
                CreationDate = x.CreationDate,
                EmployeeFullName = x.Employee.FullName,
                RealizationDate = x.RealizationDate,
                Status = x.Status
            }).ToList();

            return View(orders);
        }
        public ActionResult Edit(int id)
        {
            @ViewBag.Contractors = new SelectList(_cService.GetAll(), "Id", "Name");
            @ViewBag.Articles = new SelectList(_aService.GetAll(), "Id", "Name");

            var order = _oService.GetOrder(id);

            var orderRows = _oService.GetOrderRows(id);
            ViewBag.Rows = orderRows.Count();
            OrderEditModelView model = new OrderEditModelView
            {
                Code = order.Code,
                ContractorId = order.ContractorId,
                Id = order.Id,
                RealizationDate = order.RealizationDate,
                Status = order.Status,
                CreationDate = order.CreationDate,
                OrderRows = orderRows,
                EmployeeId = order.EmployeeId

            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(OrderEditModelView model, int[] ArticleId, int[] Amount, decimal[] Price)
        {
            if (ModelState.IsValid)
            {
                Order order = new Order
                {
                    Code = model.Code,
                    ContractorId = model.ContractorId,
                    CreationDate = DateTime.Now,
                    EmployeeId = _lService.GetEmployeeId(User.Identity.Name),
                    RealizationDate = DateTime.Now,
                    Status = model.Status,
                    OrderRows = new List<OrderRow>()
                };

                for (int i = 0; i < ArticleId.Length; i++)
                {

                    OrderRow row = new OrderRow
                    {
                        ArticleId = ArticleId[i],
                        Amount = Amount[i],
                        Price = Price[i]
                    };
                    order.OrderRows.Add(row);
                }
                _oService.SaveOrder(order);


                var o = _oService.GetOrder(model.Id);
                _oService.UpdateOrder(o);
                return RedirectToAction("Index");
            }
            else
            {
                @ViewBag.Contractors = new SelectList(_cService.GetAll(), "Id", "Name");
                @ViewBag.Articles = new SelectList(_aService.GetAll(), "Id", "Name");
                return View(model);
            }
        }

        public ActionResult Create()
        {
            @ViewBag.Contractors = new SelectList(_cService.GetAll(), "Id", "Name");
            @ViewBag.Articles = new SelectList(_aService.GetAll(), "Id", "Name");

            OrderCreateModelView model = new OrderCreateModelView();
            model.Code = "ORD/" + DateTime.Now.Year + "/" + DateTime.Now.Month + "/" + DateTime.Now.Day + "/" +
                         DateTime.Now.Second + "/" + DateTime.Now.Millisecond;
            model.RealizationDate = DateTime.Now;
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(OrderCreateModelView model, int[] articleSelect, int[] amount, decimal[] price)
        {
            if (ModelState.IsValid)
            {
                Order order = new Order
                {
                    Code = model.Code,
                    ContractorId = model.ContractorId,
                    CreationDate = DateTime.Now,
                    EmployeeId = _lService.GetEmployeeId(User.Identity.Name),
                    RealizationDate = model.RealizationDate,
                    Status = Status.open,
                    OrderRows = new List<OrderRow>()
                };
                for (int i = 0; i < articleSelect.Length; i++)
                {

                    OrderRow row = new OrderRow
                    {
                        ArticleId = articleSelect[i],
                        Amount = amount[i],
                        Price = price[i]
                    };
                    order.OrderRows.Add(row);
                }
                _oService.SaveOrder(order);
                return RedirectToAction("Index");
            }
            else
            {
                @ViewBag.Contractors = new SelectList(_cService.GetAll(), "Id", "Name");
                @ViewBag.Articles = new SelectList(_aService.GetAll(), "Id", "Name");
                return View(model);
            }
        }
        public ActionResult Delete(int id)
        {
            _oService.DeleteOrder(id);
            return RedirectToAction("Index");
        }
        public ActionResult CloseOrder(int id)
        {
            _oService.CloseOrder(id);
            return RedirectToAction("Index");
        }
        public ActionResult OpenOrder(int id)
        {
            _oService.OpenOrder(id);
            return RedirectToAction("Index");
        }
    }
}

ERPProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ERPIK</title>

    <link rel="stylesheet" href=" https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--  @Html.ActionLink("ERPIK", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", style = "color:black" }) -->
                <a href='@Url.Action("Index", "Home")'>
                    <img style="height:75px;width:100px" src='@Url.Content("~/Images/erpik_logo.png")' />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li class="btn-color">
                        <a href="@Url.Action("Index", "Employee")" class="btn btn-dark">
                            <i class="fa fa-address-book" aria-hidden="true"></i>
                            <span>
                                <strong>Employees</strong>
                            </span>
                        </a>
                    </li>
                    <li class="btn-color">
                        <a href="@Url.Action("Index", "Inventory")" class="btn btn-dark">
                            <i class="fa fa-plus-square" aria-hidden="true"></i>
                            <span>
                                <strong>Inventory</strong>
                            </span>
                        </a>
                    </li>
                    <li class="btn-color">
                        <a href="@Url.Action("Index", "Contractor")" class="btn btn-dark">
                            <i class="fa fa-briefcase" aria-hidden="true"></i>
                            <span>
                                <strong>Contractor</strong>
                            </span>
                        </a>
                    </li>
                    <li class="btn-color">
                        <a href="@Url.Action("Index", "Article")" class="btn btn-dark">
                            <i class="fa fa-sitemap" aria-hidden="true"></i>
                            <span>
                                <strong>Articles</strong>
                            </span>
                        </a>
                    </li>
                    <li class="btn-color">
                        <a href="@Url.Action("Index", "Order")" class="btn btn-dark">
                            <i class="fa fa-cart-arrow-down" aria-hidden="true"></i>
                            <span>
                                <strong>Orders</strong>
                            </span>
                        </a>
                    </li>


                    <li>
                        <div class="dropdown text-center" style="padding-top: 23px">
                            <button class="btn btn-secondary dropdown-toggle text-center" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <strong>Warehouse</strong>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

                                <a href="@Url.Action("ExternalReceiptIndex", "Warehouse")" class="btn btn-dark">
                                    <i class="fa fa-arrow-circle-right" aria-hidden="true"></i>
                                    <span>
                                        <strong>External Receipts</strong>
                                    </span>
                                </a>
                                <a href="@Url.Action("ExternalReleaseIndex", "Warehouse")" class="btn btn-dark">
                                    <i class="fa fa-arrow-circle-left" aria-hidden="true"></i>
                                    <span>
                                        <strong>External Releases</strong>
                                    </span>
                                </a>
                                <a href="@Url.Action("AmortizationIndex", "Warehouse")" class="btn btn-dark">
                                    <i class="fa fa-ban" aria-hidden="true"></i>
                                    <span>
                                        <strong>Amortization</strong>
                                    </span>
                                </a>


                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown text-center" style="padding-top: 23px; padding-left: 5px">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <strong>Configuration</strong>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a href="@Url.Action("Index", "Login")" class="btn btn-dark">
                                    <i class="fa fa-address-card" aria-hidden="true"></i>

                                    <span>
                                        <strong>Operators</strong>
                                    </span>
                                </a> <br />

                            </div>
                        </div>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="btn-color">
                            <a href="@Url.Action("Index", "Order")" class="btn btn-dark">
                                <i class="fa fa-sign-out" aria-hidden="true"></i>
                                <span>
                                    <strong>Logout</strong>
                                </span>
                            </a>
                        </li>
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ERPIK</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>